# Development override for docker-compose.yml
# This file is automatically loaded when running docker-compose up
# Use this file for local development with hot reloading

services:
  # Backend API - development mode
  backend:
    build:
      context: .                # Path to the build context (Directory within Docker)
      dockerfile: backend/Dockerfile    # Name of the Dockerfile to use for building the image
      target: development #Use the development stage (includes DevDependencies)
    command: npm run dev:backend  #Use the development command with hot reloading

  # Web Dashboard - development mode
  web-dashboard:
    build:
      target: development # Use the development command with hot reloading
    command: npm run dev:web # Use the development server
