# ----------------------------------------------------------------------------
# Docker Compose Configuration for the project
# This file defines all the services needed to run Credora
#
# Services include : 
#
# Volumes include :
#
# Networks include :
#
# Environment variables include :
# ----------------------------------------------------------------------------
services:
  # Backend API
  backend:
    # Specify how to build the Docker image for the backend
    build:
      context: ./backend        # Path to the build context (Directory within Docker)
      dockerfile: Dockerfile    # Name of the Dockerfile to use for building the image

  # Web Dashboard
  web-dashboard:
    # Specify how to build the Docker image for the web dashboard
    build:
      context: ./web-dashboard  # Path to the build context (Directory within Docker)
      dockerfile: Dockerfile    # Name of the Dockerfile to use for building the image
    depends_on:
      backend:
        condition: service_healthy
